kubeStateMetrics:
  enabled: true
  kube-state-metrics:
    replicas: 2
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 32Mi
grafana:
  enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    enabled: true
    type: LoadBalancer
    port: 80
    targetPort: 3000
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPU: "60"
    targetMemory: ""
prometheus:
  enabled: true
  replicaCount: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi
  service:
    type: LoadBalancer
    port: 9090
    targetPort: 9090
alertmanager:
  enabled: false
nodeExporter:
  enabled: false
