apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: metabase
  namespace: metabase
spec:
  scaleTargetRef:
    kind: Deployment
    name: metabase
  minReplicaCount: 2
  maxReplicaCount: 15
  cooldownPeriod: 30
  pollingInterval: 1 
  triggers:
  - type: prometheus
    metricType: AverageValue
    metadata:
      serverAddress: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
      metricName: avg_http_requests
      query: |
        sum(http_requests_total{deployment="metabase"}[5m])
      threshold: "10"
  - type: cpu
    metricType: Utilization
    metadata:
      value: "100"
