apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: metabase
  namespace: metabase
spec:
  scaleTargetRef:
    kind: Deployment
    name: metabase
  minReplicaCount: 1
  maxReplicaCount: 10
  cooldownPeriod: 30
  pollingInterval: 1 
  fallback:
    failureThreshold: 1
    replicas: 1
  triggers:
  - type: prometheus
    metricType: AverageValue
    metadata:
      # serverAddress: http://k8s-monitori-monitori-258d36c54c-f8bbba58531ba4a4.elb.us-east-1.amazonaws.com/:9090
      serverAddress: http://prometheus-operated.monitoring:9090
      metricName: istio_requests_total
      query: |
        sum(istio_requests_total{destination_workload="metabase"})
      threshold: "100"
  - type: memory
    metricType: Utilization
    metadata:
      value: "150"
