apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: metabase
  namespace: metabase
spec:
  scaleTargetRef:
    kind: Deployment
    name: metabase
  minReplicaCount: 1
  maxReplicaCount: 10
  cooldownPeriod: 30
  pollingInterval: 1
  fallback:
    failureThreshold: 3
    replicas: 3  
  triggers:
  - type: prometheus
    metricType: AverageValue
    metadata:
      serverAddress: http://prometheus-operated.monitoring.svc.cluster.local:9090
      metricName: avg_http_requests
      query: |
        sum(http_requests_total{deployment="metabase"}[5m]))
      threshold: "10"
  - type: memory
    metricType: Utilization
    metadata:
      value: "100"
