apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: metabase
  namespace: metabase
  annotations:
    scaledobject.keda.sh/transfer-hpa-ownership: "true"
spec:
  scaleTargetRef:
    name: metabase
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 3
  cooldownPeriod: 15
  idleReplicaCount: 0
  fallback:
    failureThreshold: 3
    replicas: 3
  advanced:
    horizontalPodAutoscalerConfig:
      name: metabase
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-kube-prometheus-stack-server.monitoring.svc.cluster.local
        query: sum(rate(http_server_requests_seconds_count{uri="/api/database/1/metadata",job="metabase"}[1m])) by (job)
        threshold: "1000"
        activationThreshold: "1"
      useCachedMetrics: true
      metricType: AverageValue
