database:
  type: mysql
  port: 3306
javaOpts: "-XX:+UseSerialGC"
livenessProbe:
  initialDelaySeconds: 120
  timeoutSeconds: 30
  failureThreshold: 6
readinessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 3
  periodSeconds: 5
service:
  type: ClusterIP
resources:
  requests:
    cpu: 500m
    memory: 500Mi
