replicaCount: 1
database:
  type: mysql
  host: ${{ RDS_ENDPOINT }}
  port: ${{ DB_PORT }}
  dbname: ${{ DB_NAME }}
  username: ${{ DB_USERNAME }}
  password: ${{ RDS_PASSWORD }}
resources:
  requests:
    cpu: 500m
    memory: 500Mi
  limits:
    cpu: 800m
    memory: 700Mi
javaOpts: "-XX:+UseSerialGC"
livenessProbe:
  initialDelaySeconds: 120
  timeoutSeconds: 30
  failureThreshold: 6
readinessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 3
  periodSeconds: 5
service:
  type: ClusterIP
ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: "${aws_acm_certificate.metabase_cert.arn}"
  hosts:
    - metabasekaiolab.com
  path: /
  pathType: Exact
  tls:
    - secretName: metabase-tls
      hosts:
        - metabasekaiolab.com
