replicaCount: 1
database:
  type: mysql
  host: ${{ RDS_ENDPOINT }}
  port: ${{ DB_PORT }}
  dbname: ${{ DB_NAME }}
  username: ${{ DB_USERNAME }}
  password: ${{ RDS_PASSWORD }}
resources:
  requests:
    cpu: 500m
    memory: 768Mi
  limits:
    cpu: 800m
    memory: 700Mi
javaOpts: "-XX:+UseSerialGC"
livenessProbe:
  initialDelaySeconds: 120
  timeoutSeconds: 30
  failureThreshold: 6
readinessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 3
  periodSeconds: 5
service:
  type: ClusterIP
