operator:
  replicaCount: 2
prometheus:
  metricServer:
    enabled: true
    serviceMonitor:
      enabled: true
    podMonitor:
      enabled: true
  operator:
    enabled: true
    serviceMonitor:
      enabled: true
    podMonitor:
      enabled: true
  webhooks:
    enabled: true
    serviceMonitor:
      enabled: true
logging:
  operator:
    level: info
  metricServer:
    level: 4
  webhooks:
    level: info
  