operator:
  serviceMonitor:
    enabled: true
  replicaCount: 2
prometheus:
  metricServer:
    enabled: true
    serviceMonitor:
      enabled: true
    podMonitor:
      enabled: true
    useHostNetwork: true
