name: Apply Infrastructure

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1'
  EKS_CLUSTER_NAME: 'metabase-lab'
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PORT: ${{ secrets.DB_PORT }}
  RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
  RDS_ENDPOINT: ${{ secrets.RDS_ENDPOINT }}
  TF_VAR_db_name: ${{ secrets.DB_NAME }}
  TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
  TF_VAR_db_port: ${{ secrets.DB_PORT }}

on:
  push:
    branches:
      - main

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
    - name: Set short git commit SHA
      id: commit
      uses: prompt/actions-commit-hash@v2

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{env.AWS_DEFAULT_REGION}}

    - name: Update kube config
      run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_DEFAULT_REGION

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: Terraform Apply
      run: |
        cd environments/lab
        pwd
        ls -la
        terraform init
        terraform apply -auto-approve

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.5.4'

    - name: Apply kube-prometheus-stack
      run: |
        cd helm/kube-prometheus-stack
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update
        helm upgrade -i kube-prometheus-stack prometheus-community/kube-prometheus-stack --namespace monitoring -f values.yaml
