name: Deploy Infrastructure

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-west-2'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    # Apply Backend Configuration
    - name: Terraform Init in Backend
      run: |
        cd infra/state-backend
        terraform init

    # Apply VPC Configuration
    - name: Terraform Init in VPC
      run: |
        cd infra/vpc
        terraform init
    - name: Terraform Apply in VPC
      run: |
        cd infra/vpc
        terraform apply -auto-approve
