name: Deploy Infrastructure

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-west-2'
  RDS_ENDPOINT: ${{ secrets.RDS_ENDPOINT }}
  RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
  TF_VAR_db_name: ${{ secrets.DB_NAME }}
  TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
  TF_VAR_db_port: ${{ secrets.DB_PORT }}
  TF_VAR_rds_endpoint: ${{ secrets.RDS_ENDPOINT }}
  TF_VAR_rds_password: ${{ secrets.RDS_PASSWORD }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    # # Apply Backend Configuration
    # - name: Terraform Init in Backend
    #   run: |
    #     cd infra/state-backend
    #     terraform init
    - name: Configure Kubernetes Context
      run: |
        echo "${{ secrets.KUBECONFIG_FILE }}" > kubeconfig.yaml
        export KUBECONFIG=$(pwd)/kubeconfig.yaml
        kubectl config use-context your-cluster-context
      env:
        KUBECONFIG: kubeconfig.yaml

    - name: Terraform Init
      run: |
        cd infra
        terraform init
    - name: Terraform Apply
      run: |
        cd infra
        terraform apply -auto-approve

    - name: Deploy Metabase
      run: |
        cd infra/stack/metabase
        helm repo add pmint93 https://pmint93.github.io/helm-charts
        helm repo update
        helm install metabase pmint93/metabase -f values.yaml
