name: Cluster Stack Management

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1'
  EKS_CLUSTER_NAME: 'metabaselab'
  RDS_ENDPOINT: ${{ secrets.RDS_ENDPOINT }}
  RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
  DB_NAME: "metabaselab"
  DB_USERNAME: "metabaselab"
  DB_PORT: "3306"

on:
  workflow_dispatch:
    inputs:
      components:
        description: 'Comma-separated list of components to apply (e.g., istio,metabase)'
        required: true

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_DEFAULT_REGION

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.13.3'

      # Helm Operation for KEDA
      - name: Helm install KEDA
        if: contains(github.event.inputs.components, 'keda')
        run: |
          helm repo add kedacore https://kedacore.github.io/charts
          helm repo update
          cd helm/keda
          helm upgrade --install keda kedacore/keda --namespace keda -f values.yaml --create-namespace
          kubectl apply -f metabase-scaledobject.yaml && kubectl apply -f istio-scaledobject.yaml

      - name: Helm install Istio
        if: contains(github.event.inputs.components, 'istio')
        run: |
          helm repo add istio https://istio-release.storage.googleapis.com/charts
          helm repo update
          cd helm/istio
          helm upgrade --install istio-base istio/base -n istio-system --create-namespace --set defaultRevision=default
          helm upgrade --install istiod istio/istiod -n istio-system -f istiod-values.yaml --wait
          kubectl apply -f gateway.yaml -n && kubectl apply -f grafana-vs.yaml && kubectl apply -f prometheus-vs.yaml && kubectl apply -f metabase-vs.yaml && kubectl apply -f podmonitor.yaml && kubectl apply -f servicemonitor.yaml

      - name: Helm install kube-prometheus-stack
        if: contains(github.event.inputs.components, 'prometheus')
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          cd helm/kube-prometheus-stack
          helm upgrade --install kube-prometheus-stack prometheus-community/kube-prometheus-stack --namespace monitoring -f values.yaml --create-namespace
          kubectl apply -f keda-dashboard.yaml

      - name: Install metrics-server
        if: contains(github.event.inputs.components, 'metrics-server')
        run: |
          kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/high-availability-1.21+.yaml

      - name: Helm install Metabase
        if: contains(github.event.inputs.components, 'metabase')
        run: |
          helm repo add pmint93 https://pmint93.github.io/helm-charts
          helm repo update
          cd helm/metabase
          helm upgrade --install metabase pmint93/metabase --namespace metabase -f values.yaml --create-namespace \
            --set database.host="${{ secrets.RDS_ENDPOINT }}" \
            --set database.dbname="${{ secrets.DB_NAME }}" \
            --set database.username="${{ secrets.DB_USERNAME }}" \
            --set database.password="${{ secrets.RDS_PASSWORD }}"

      - name: Istio injection for Metabase
        run: |
          kubectl label namespace metabase istio-injection=enabled
