name: Helm Infrastructure Management

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1'
  EKS_CLUSTER_NAME: 'metabase-lab'
  RDS_ENDPOINT: ${{ secrets.RDS_ENDPOINT }}
  RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
  DB_NAME: "metabase"
  DB_USERNAME: "metabase"
  DB_PORT: "3306"

on:
  workflow_dispatch:
    inputs:
      helm_action:
        description: 'Helm action to perform (plan/apply/uninstall)'
        required: true
        default: 'plan'

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_DEFAULT_REGION

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.5.4'

      - name: Helm Operation for kube-prometheus-stack
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          cd helm/kube-prometheus-stack
          if [ "${{ github.event.inputs.helm_action }}" == "plan" ]; then
            helm template kube-prometheus-stack . --namespace monitoring -f values.yaml
          elif [ "${{ github.event.inputs.helm_action }}" == "apply" ]; then
            helm upgrade --install kube-prometheus-stack . --namespace monitoring -f values.yaml --create-namespace
          elif [ "${{ github.event.inputs.helm_action }}" == "uninstall" ]; then
            helm uninstall kube-prometheus-stack --namespace monitoring
          fi
