name: Infrastructure Management

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1'
  EKS_CLUSTER_NAME: 'metabase-lab'
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PORT: ${{ secrets.DB_PORT }}
  RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
  RDS_ENDPOINT: ${{ secrets.RDS_ENDPOINT }}
  TF_VAR_db_name: ${{ secrets.DB_NAME }}
  TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
  TF_VAR_db_port: ${{ secrets.DB_PORT }}

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (apply/destroy)'
        required: true
        default: 'apply'

jobs:
  manage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: Update kube config
      run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_DEFAULT_REGION

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.5.4' # Specify the desired version of Helm

    - name: Helm Upgrade/Install Karpenter CRDs
      if: github.event.inputs.action != 'destroy'
      run: helm upgrade --install karpenter-crd oci://public.ecr.aws/karpenter/karpenter-crd --version v0.32.5 --namespace karpenter --create-namespace

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Apply or Destroy
      run: |
        cd environments/lab
        terraform init
        action=${{ github.event.inputs.action }}
        if [ "$action" == "destroy" ]; then
          terraform destroy -auto-approve
        else
          terraform apply -auto-approve
        fi
