name: Manual Infrastructure Stack Management

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1'
  TF_VAR_db_password: ${{ secrets.RDS_PASSWORD }}
  EKS_CLUSTER_NAME: 'metabaselab'

on:
  workflow_dispatch:
    inputs:
      terraform_components:
        description: 'Comma-separated list of Terraform components to apply (e.g., vpc,security_group,eks,rds,karpenter)'
        required: true
        default: 'vpc,eks,rds'

jobs:
  apply-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Initialize
        run: |
          cd environments/lab
          terraform init

      # Conditional Terraform Operations for each component
      - name: Terraform Apply VPC
        if: contains(github.event.inputs.terraform_components, 'vpc')
        run: |
          cd environments/lab
          terraform apply -target=module.lab_vpc -auto-approve

      - name: Terraform Apply EKS
        if: contains(github.event.inputs.terraform_components, 'eks')
        run: |
          cd environments/lab
          terraform apply -target=module.eks_fargate_karpenter.module.eks -auto-approve

      - name: Terraform Apply RDS
        if: contains(github.event.inputs.terraform_components, 'rds')
        run: |
          cd environments/lab
          terraform apply -target=module.lab_rds -auto-approve

      - name: Terraform Apply RDS Security Group
        if: contains(github.event.inputs.terraform_components, 'rds')
        run: |
          cd environments/lab
          terraform apply -target=module.security_group -auto-approve

      # At this point, since the previous components are already set up,
      # terraform will only apply Karpenter and its dependencies.
      - name: Terraform Apply Karpenter and AWS Load Balancer Controller
        if: contains(github.event.inputs.terraform_components, 'eks')
        run: |
          cd environments/lab
          terraform apply -auto-approve
