name: Plan Destroy Infrastructure

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-west-2'
  TF_VAR_db_name: ${{ secrets.DB_NAME }}
  TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
  TF_VAR_db_port: ${{ secrets.DB_PORT }}

on: 
  workflow_dispatch:

jobs:
  plan-destroy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Initialize
      run: |
        cd infra
        terraform init

    - name: Terraform Plan Destroy
      run: |
        cd infra
        terraform plan -destroy -out=plan-destroy
